# Mandar cambios de repo a pruebas manuales
name: Pruebas manuales

on: 
  push:
    branches: [ pruebas-manuales ]

jobs:
  pruebas-manuales:
    runs-on: ubuntu-latest
    steps:

      # Entrar a la MV de pruebas manuales y bajar
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/educ2-4/
            git config --global --add safe.directory /var/www/html/***2-4
            git pull educ25 sandoval
